# Meta Data for SEO

## Homepage
title = "Gowri Shankar"
titleSeparator = "-"
titleAddition = "Portfolio of Gowri Shankar"
description = "PRINCIPAL ARCHITECT | PRODUCT OWNER | DATA SCIENCE ENTHUSIAST | KAGGLE EXPERT | SOFTWARE QUALITY FREAK 18+ Years, A Heartful Programmer"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "gowrishankarin"
twitterCreator = "gowrishankarin"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/gowrishankarin"
schemaLinkedIn = "https://www.linkedin.com/in/gowrishankarin/"
schemaGitHub = "https://github.com/gowrishankarin"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Copyright 2021 <a href=\"https://www.gowrishankar.info/\">GowriShankar.info</a> All rights reserved"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false
